title: Shunyao Wu
description: Personal introduction page
theme: null   # or "minimal-mistakes-jekyll" if you want more features
baseurl: ""     # keep empty
url: "https://shunyao-wu.github.io"
plugins:
  - jekyll-feed